### ISSUE TITLE
composer install失敗

### ISSUE THREAD

**Issue by carlkyo** [imajinyun/laravel-bbs#42]
直接用composer install顯示
λ composer install
No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.

Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laravel/horizon ^5.9 -> satisfiable by laravel/horizon[v5.9.0, ..., 5.x-dev].
    - laravel/horizon[v5.9.0, ..., 5.x-dev] require ext-pcntl * -> it is missing from your system. Install or enable PHP's pcntl extension.
  Problem 2
    - php-amqplib/php-amqplib[dev-master, 3.0.0-rc1, ..., v3.4.0] require ext-sockets * -> it is missing from your system. Install or enable PHP's sockets extension.
    - php-amqplib/php-amqplib v3.0.0 requires php ^7.0|~8.0.0 -> your php version (8.1.10) does not satisfy that requirement.
    - vladimir-yuldashev/laravel-queue-rabbitmq[v12.0.0, ..., v12.0.x-dev] require php-amqplib/php-amqplib ^3.0 -> satisfiable by php-amqplib/php-amqplib[3.0.0-rc1, ..., v3.4.0].
    - php-amqplib/php-amqplib 3.0.x-dev is an alias of php-amqplib/php-amqplib dev-master and thus requires it to be installed too.
    - Root composer.json requires vladimir-yuldashev/laravel-queue-rabbitmq ^12.0 -> satisfiable by vladimir-yuldashev/laravel-queue-rabbitmq[v12.0.0, v12.0.1, v12.0.x-dev].

To enable extensions, verify that they are enabled in your .ini files:
    - C:\Users\Public\laragon\bin\php\php-8.1.10-Win32-vs16-x64\php.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-pcntl --ignore-platform-req=ext-sockets` to temporarily ignore these required extensions.

用了composer install --ignore-platform-reqs最後又出現
謝謝
> @php artisan package:discover --ansi

   Symfony\Component\ErrorHandler\Error\FatalError

  Declaration of VladimirYuldashev\LaravelQueueRabbitMQ\Consumer::stop($status = 0): int must be compatible with Illuminate\Queue\Worker::stop($status = 0, $options = null)

  at C:\Users\Public\laragon\www\bbs\vendor\vladimir-yuldashev\laravel-queue-rabbitmq\src\Consumer.php:200
    196▕      *
    197▕      * @param  int  $status
    198▕      * @return int
    199▕      */
  ➜ 200▕     public function stop($status = 0): int
    201▕     {
    202▕         // Tell the server you are going to stop consuming.
    203▕         // It will finish up the last message and not send you any more.
    204▕         $this->channel->basic_cancel($this->consumerTag, false, true);

   Whoops\Exception\ErrorException

  Declaration of VladimirYuldashev\LaravelQueueRabbitMQ\Consumer::stop($status = 0): int must be compatible with Illuminate\Queue\Worker::stop($status = 0, $options = null)

  at C:\Users\Public\laragon\www\bbs\vendor\vladimir-yuldashev\laravel-queue-rabbitmq\src\Consumer.php:200
    196▕      *
    197▕      * @param  int  $status
    198▕      * @return int
    199▕      */
  ➜ 200▕     public function stop($status = 0): int
    201▕     {
    202▕         // Tell the server you are going to stop consuming.
    203▕         // It will finish up the last message and not send you any more.
    204▕         $this->channel->basic_cancel($this->consumerTag, false, true);

  1   C:\Users\Public\laragon\www\bbs\vendor\filp\whoops\src\Whoops\Run.php:486
      Whoops\Run::handleError("Declaration of VladimirYuldashev\LaravelQueueRabbitMQ\Consumer::stop($status = 0): int must be compatible with Illuminate\Queue\Worker::stop($status = 0, $options = null)", "C:\Users\Public\laragon\www\bbs\vendor\vladimir-yuldashev\laravel-queue-rabbitmq\src\Consumer.php")

  2   [internal]:0
      Whoops\Run::handleShutdown()
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255

**Comment by imajinyun** [comment]
已经升级到最新的 Laravel 版本上。
